/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package JoueurCrud;

import ig.Connecteur;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.JOptionPane;
import javax.swing.JScrollPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author LENOVO
 */
public class AfficherCompetitions extends javax.swing.JInternalFrame {

    /**
     * Creates new form AfficherCompetitions
     */
    public AfficherCompetitions() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jPanel12 = new javax.swing.JPanel();
        jLabel34 = new javax.swing.JLabel();
        type_comt = new javax.swing.JComboBox<>();
        resetaff8 = new javax.swing.JButton();
        VIEW_COMPT8 = new javax.swing.JButton();
        date_min = new javax.swing.JSpinner();
        date_max = new javax.swing.JSpinner();
        jLabel35 = new javax.swing.JLabel();
        jLabel36 = new javax.swing.JLabel();
        jLabel37 = new javax.swing.JLabel();
        cancel = new javax.swing.JButton();

        setBackground(new java.awt.Color(255, 255, 255));
        setAutoscrolls(true);
        setPreferredSize(new java.awt.Dimension(605, 3408));
        setVisible(true);

        jLabel34.setFont(new java.awt.Font("Arial Black", 3, 24)); // NOI18N
        jLabel34.setText("Afficher les compétitions");

        type_comt.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "All", "Professionnel", "Senior", "Amateur", " " }));
        type_comt.setName("competition_types"); // NOI18N

        resetaff8.setBackground(new java.awt.Color(255, 102, 0));
        resetaff8.setText("réinitialiser");
        resetaff8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                resetaff8ActionPerformed(evt);
            }
        });

        VIEW_COMPT8.setBackground(new java.awt.Color(0, 153, 51));
        VIEW_COMPT8.setText("valider");
        VIEW_COMPT8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                VIEW_COMPT8ActionPerformed(evt);
            }
        });

        date_min.setModel(new javax.swing.SpinnerDateModel());

        date_max.setModel(new javax.swing.SpinnerDateModel());

        jLabel35.setFont(new java.awt.Font("Arial Black", 3, 12)); // NOI18N
        jLabel35.setForeground(java.awt.Color.darkGray);
        jLabel35.setText("Date min");

        jLabel36.setFont(new java.awt.Font("Arial Black", 3, 12)); // NOI18N
        jLabel36.setForeground(java.awt.Color.darkGray);
        jLabel36.setText("Date max");

        jLabel37.setFont(new java.awt.Font("Arial Black", 3, 12)); // NOI18N
        jLabel37.setForeground(java.awt.Color.darkGray);
        jLabel37.setText("type de compétition");

        cancel.setBackground(new java.awt.Color(255, 102, 0));
        cancel.setText("cancel");
        cancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel12Layout = new javax.swing.GroupLayout(jPanel12);
        jPanel12.setLayout(jPanel12Layout);
        jPanel12Layout.setHorizontalGroup(
            jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel12Layout.createSequentialGroup()
                .addGroup(jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel12Layout.createSequentialGroup()
                        .addGap(190, 190, 190)
                        .addGroup(jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel36, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel35, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(date_min, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(date_max, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel12Layout.createSequentialGroup()
                        .addGap(212, 212, 212)
                        .addGroup(jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(type_comt, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel37, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel12Layout.createSequentialGroup()
                        .addGap(100, 100, 100)
                        .addComponent(jLabel34, javax.swing.GroupLayout.PREFERRED_SIZE, 363, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel12Layout.createSequentialGroup()
                        .addGap(111, 111, 111)
                        .addComponent(VIEW_COMPT8, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(133, 133, 133)
                        .addComponent(resetaff8, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel12Layout.createSequentialGroup()
                        .addGap(237, 237, 237)
                        .addComponent(cancel, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(189, 369, Short.MAX_VALUE))
        );
        jPanel12Layout.setVerticalGroup(
            jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel12Layout.createSequentialGroup()
                .addComponent(jLabel34, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addGroup(jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(date_min, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel35))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel36, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(date_max, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel37)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(type_comt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(resetaff8)
                    .addComponent(VIEW_COMPT8))
                .addGap(84, 84, 84)
                .addComponent(cancel, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(46, Short.MAX_VALUE))
        );

        jScrollPane1.setViewportView(jPanel12);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 593, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 372, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void resetaff8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_resetaff8ActionPerformed
 type_comt.setSelectedIndex(0);
    }//GEN-LAST:event_resetaff8ActionPerformed

    private void VIEW_COMPT8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_VIEW_COMPT8ActionPerformed
        String type;
        type = (String)type_comt.getSelectedItem();
        Date datemin=(Date)date_min.getValue();
        Date datemax=(Date)date_max.getValue();
        SimpleDateFormat sdf = new SimpleDateFormat("yyyy-MM-dd");
        String datemina = sdf.format(datemin);
        String datemaxa = sdf.format(datemax);
        Connection con;
        Connecteur connect=new Connecteur();
        con = connect.connecttodb();
        if (type.equals("All")){
            try
            {
                Statement stmt = con.createStatement(ResultSet.TYPE_SCROLL_INSENSITIVE,ResultSet.CONCUR_READ_ONLY);
                String st = ("SELECT * FROM competition WHERE competition.date_compt BETWEEN '"+datemina+"' AND '"+datemaxa+"';");
                ResultSet rs = stmt.executeQuery(st);
                DefaultTableModel tableModel = new DefaultTableModel();
                java.sql.ResultSetMetaData metaData = rs.getMetaData();
                int columnCount = metaData.getColumnCount();
                for (int i = 1; i <= columnCount; i++) {
                    tableModel.addColumn(metaData.getColumnName(i));
                }
                while (rs.next()) {
                    Object[] row = new Object[columnCount];
                    for (int i = 1; i <= columnCount; i++) {
                        row[i - 1] = rs.getObject(i);
                    }
                    tableModel.addRow(row);

                }
                String titre;
                titre = "liste des competition entre"+dateminAff+" et "+datemaxAff;
                // Create a JTable and display the data
                JTable table = new JTable(tableModel);
                JOptionPane.showMessageDialog(null, new JScrollPane(table), titre, JOptionPane.PLAIN_MESSAGE);
            }
            catch(SQLException ex){
                JOptionPane.showMessageDialog(null,"Probleme dans la base de données");
            }
        }
        else
        try
        {
            Statement stmt = con.createStatement(ResultSet.TYPE_SCROLL_INSENSITIVE,ResultSet.CONCUR_READ_ONLY);
            String st = ("SELECT competition.*,type_compt.nom_type,type_compt.recompense FROM competition,type_compt WHERE competition.date_compt BETWEEN '"+datemina+"' AND '"+datemaxa+"' and type_compt.id_type=competition.id_type and type_compt.nom_type='"+type+"';");
            ResultSet rs = stmt.executeQuery(st);
            DefaultTableModel tableModel = new DefaultTableModel();
            java.sql.ResultSetMetaData metaData = rs.getMetaData();
            int columnCount = metaData.getColumnCount();
            for (int i = 1; i <= columnCount; i++) {
                tableModel.addColumn(metaData.getColumnName(i));
            }
            while (rs.next()) {
                Object[] row = new Object[columnCount];
                for (int i = 1; i <= columnCount; i++) {
                    row[i - 1] = rs.getObject(i);
                }
                tableModel.addRow(row);
                JTable table = new JTable(tableModel);
                String titre;
                titre = "liste des competition "+type+" entre"+dateminAff+" et "+datemaxAff;

            }

            // Create a JTable and display the data
            JTable table = new JTable(tableModel);
            JOptionPane.showMessageDialog(null, new JScrollPane(table), "liste des competition", JOptionPane.PLAIN_MESSAGE);
        }
        catch(SQLException ex){
            JOptionPane.showMessageDialog(null,"Probleme dans la base de données");
        }

        // TODO add your handling code here:
    }//GEN-LAST:event_VIEW_COMPT8ActionPerformed

    private void cancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelActionPerformed
this.dispose();        // TODO add your handling code here:
    }//GEN-LAST:event_cancelActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton VIEW_COMPT;
    private javax.swing.JButton VIEW_COMPT1;
    private javax.swing.JButton VIEW_COMPT2;
    private javax.swing.JButton VIEW_COMPT3;
    private javax.swing.JButton VIEW_COMPT4;
    private javax.swing.JButton VIEW_COMPT5;
    private javax.swing.JButton VIEW_COMPT6;
    private javax.swing.JButton VIEW_COMPT7;
    private javax.swing.JButton VIEW_COMPT8;
    private javax.swing.JButton cancel;
    private javax.swing.JSpinner date_max;
    private javax.swing.JSpinner date_min;
    private javax.swing.JSpinner datemaxAff;
    private javax.swing.JSpinner datemaxAff1;
    private javax.swing.JSpinner datemaxAff2;
    private javax.swing.JSpinner datemaxAff3;
    private javax.swing.JSpinner datemaxAff4;
    private javax.swing.JSpinner datemaxAff5;
    private javax.swing.JSpinner datemaxAff6;
    private javax.swing.JSpinner datemaxAff7;
    private javax.swing.JSpinner dateminAff;
    private javax.swing.JSpinner dateminAff1;
    private javax.swing.JSpinner dateminAff2;
    private javax.swing.JSpinner dateminAff3;
    private javax.swing.JSpinner dateminAff4;
    private javax.swing.JSpinner dateminAff5;
    private javax.swing.JSpinner dateminAff6;
    private javax.swing.JSpinner dateminAff7;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel37;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel12;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton resetaff;
    private javax.swing.JButton resetaff1;
    private javax.swing.JButton resetaff2;
    private javax.swing.JButton resetaff3;
    private javax.swing.JButton resetaff4;
    private javax.swing.JButton resetaff5;
    private javax.swing.JButton resetaff6;
    private javax.swing.JButton resetaff7;
    private javax.swing.JButton resetaff8;
    private javax.swing.JComboBox<String> type_compt;
    private javax.swing.JComboBox<String> type_compt1;
    private javax.swing.JComboBox<String> type_compt2;
    private javax.swing.JComboBox<String> type_compt3;
    private javax.swing.JComboBox<String> type_compt4;
    private javax.swing.JComboBox<String> type_compt5;
    private javax.swing.JComboBox<String> type_compt6;
    private javax.swing.JComboBox<String> type_compt7;
    private javax.swing.JComboBox<String> type_comt;
    // End of variables declaration//GEN-END:variables
}
